/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.shiva.krishna.jewellers;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.DatatypeConverter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import static pkgnew.shiva.krishna.jewellers.PasswordChange.decode;

/**
 *
 * @author sarfraz
 */
public class AuthPasswordChange extends javax.swing.JFrame {

    /**
     * Creates new form AuthPasswordChange
     */
    public AuthPasswordChange() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oldPassTv = new javax.swing.JPasswordField();
        newPassTv = new javax.swing.JPasswordField();
        cnewPassTv = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(600, 330));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Authorization Password Change", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Old Password        :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("New Password      :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Confirm Password :");

        oldPassTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        newPassTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cnewPassTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newPassTv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(oldPassTv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnewPassTv))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(oldPassTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newPassTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnewPassTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String oldPass = oldPassTv.getText();
       String newPass = newPassTv.getText();
       String cnewPass = cnewPassTv.getText();
       if(!getOldPassword().equals(oldPass)){
           AlertMessage msg = new AlertMessage("Wrong old password");
       }else{
           if(!newPass.equals(cnewPass) || newPass.equals("")){
               AlertMessage msg = new AlertMessage("Password Missmatch or field is blank");
           }else{
               saveNewPassword(newPass);
               AlertMessage msg = new AlertMessage("Your Authorization Password Changed Successfully");
               dispose();
           }
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getOldPassword(){
        String p = "auth@123";
        File f = new File(Constants.APPLICATION_DATA);
        JSONArray array = JsonClass.getJsonArray(Constants.APPLICATION_DATA);
        JSONParser parser = new JSONParser();
        if (f.exists() && array.size() > 2) {
            try {
                Object o = parser.parse(array.get(2).toString());
                JSONObject obj = (JSONObject) o;
                p = decode(obj.get("xxxxx").toString());
            } catch (ParseException ex) {
                Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return p;
    }
    public void saveNewPassword(String s){
        JSONParser parser = new JSONParser();
        JSONArray array = JsonClass.getJsonArray(Constants.APPLICATION_DATA);
        JSONArray newArray = new JSONArray();
        if (array.size() > 2) {
            for (int i = 0; i < array.size(); i++) {
                if (i == 2) {
                    JSONObject obj = new JSONObject();
                    obj.put("xxxxx", encode(s));
                    newArray.add(obj);
                    FileWriter.write(Constants.APPLICATION_DATA, newArray.toString());
                } else {
                    newArray.add(array.get(i));
                }
            }
        } else {
            JSONObject obj = new JSONObject();
            obj.put("xxxxx", encode(s));
            array.add(obj);
            FileWriter.write(Constants.APPLICATION_DATA, array.toString());
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    }

    public String encode(String s) {
        String encoded = "";
        try {
            byte[] message = s.getBytes("UTF-8");
            encoded = DatatypeConverter.printBase64Binary(message);

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Activation.class.getName()).log(Level.SEVERE, null, ex);
        }
        return encoded;
    }

    public static String decode(String s) {
        String r = "";
        try {
            byte[] decoded;

            decoded = DatatypeConverter.parseBase64Binary(s);
            r = new String(decoded, "UTF-8");;

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Activation.class.getName()).log(Level.SEVERE, null, ex);
        }
        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnewPassTv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newPassTv;
    private javax.swing.JPasswordField oldPassTv;
    // End of variables declaration//GEN-END:variables
}
