/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.shiva.krishna.jewellers;

import com.onbarcode.barcode.Code39;
import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author sarfraz
 */
public class Barcode39Generator extends javax.swing.JFrame {

    String path = "";
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    String dispUnit[];
    String availableQty[];
    String salePrice[];
    String itemCarret[];
    String stockID[];
    int index;

    public Barcode39Generator() {
        initComponents();

        File filePath = new File(Constants.STOCK_FILE);
        if (filePath.exists()) {
            JSONParser parser = new JSONParser();

            JSONArray array = JsonClass.getJsonArray(Constants.STOCK_FILE);
            String s[] = new String[array.size()];
            dispUnit = new String[array.size()];
            availableQty = new String[array.size()];
            salePrice = new String[array.size()];
            itemCarret = new String[array.size()];
            stockID = new String[array.size()];

            for (int i = 0; i < array.size(); i++) {
                try {
                    Object o = parser.parse(array.get(i).toString());
                    JSONObject obj = (JSONObject) o;
                    //model.addRow(new Object[] {obj.get("id"),obj.get("name"),obj.get("purchasePrice"),obj.get("salePrice"), obj.get("unit")});
                    //s[i] = obj.get("name").toString();
                    model.addElement(obj.get("name"));
                    dispUnit[i] = obj.get("unit").toString();
                    availableQty[i] = obj.get("remainingPieces").toString();
                    salePrice[i] = obj.get("salePrice").toString();
                    itemCarret[i] = obj.get("carret").toString();
                    stockID[i] = obj.get("id").toString();
                } catch (ParseException ex) {
                    Logger.getLogger(ManageItems.class.getName()).log(Level.SEVERE, null, ex);
                }

                //model.addRow(new Object[] {"one","two","three","four","five"});
            }
            //model = new DefaultComboBoxModel(s);
            /*availableTv.setText(availableQty[index]);
             salePriceField.setText(salePrice[index]);
             unitTv.setText(dispUnit[index]);
             sideUnitTv.setText(dispUnit[index]);
             unitSaleField.setText("/ "+dispUnit[index]);
             labourCostFieldUnit.setText("/ "+dispUnit[index]);
             SaleItemCarret.setText(itemCarret[index]);*/

            unitText.setText(dispUnit[0]);
            quantityUnit.setText(dispUnit[0]);
            salePriceUnit.setText(" / " + dispUnit[0]);
            labourCostUnit.setText(" / " + dispUnit[0]);

        } else {
            //String s[] = {"No item in the stock"};
            //noItem = true;
            model.addElement("No Items in the stock");
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        itemCarretEt = new javax.swing.JTextField();
        itemQuantityEt = new javax.swing.JTextField();
        SalePriceEt = new javax.swing.JTextField();
        labourCostEt = new javax.swing.JTextField();
        unitText = new javax.swing.JLabel();
        quantityUnit = new javax.swing.JLabel();
        salePriceUnit = new javax.swing.JLabel();
        labourCostUnit = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pathTv = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Barcode Generator");
        setLocation(new java.awt.Point(670, 330));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generate Barcode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Item Name         ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Carret                ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Quantity             ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Sale Price          ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Labour Cost                 ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Unit Of Measurement    ");

        itemCarretEt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        itemCarretEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCarretEtActionPerformed(evt);
            }
        });

        unitText.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        unitText.setText("N/A");

        quantityUnit.setText("unit");

        salePriceUnit.setText("/ unit");

        labourCostUnit.setText("/ unit");

        itemComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        itemComboBox.setModel(model);
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Choose Directory To save Barcode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Directory : ");

        pathTv.setText("             Not Selected");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathTv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(itemCarretEt, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(itemQuantityEt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(salePriceUnit)
                                                    .addComponent(quantityUnit)
                                                    .addComponent(labourCostUnit)))
                                            .addComponent(itemComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(unitText)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(SalePriceEt, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                                .addComponent(labourCostEt)))))))
                        .addContainerGap(29, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(itemCarretEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemQuantityEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityUnit))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SalePriceEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salePriceUnit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labourCostEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labourCostUnit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(unitText))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathTv)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        path = Helper.choseDir();
        pathTv.setText(path);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        index = itemComboBox.getSelectedIndex();
        unitText.setText(dispUnit[index]);
        quantityUnit.setText(dispUnit[index]);
        salePriceUnit.setText(" / " + dispUnit[index]);
        labourCostUnit.setText(" / " + dispUnit[index]);
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void itemCarretEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCarretEtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCarretEtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (path.equals("") || path.equals("cancelled")) {
            AlertMessage msg = new AlertMessage("Please select the path to store barcode");
        } else {
            String itemName = itemComboBox.getSelectedItem().toString();
            String itemCarretText = itemCarretEt.getText();
            String quantity = itemQuantityEt.getText();
            String salePrice = SalePriceEt.getText();
            String labourCost = labourCostEt.getText();
            
            if(itemName.equals("")){
                AlertMessage msg = new AlertMessage("Item name is required");
            }else if(itemCarretText.equals("")){
                AlertMessage msg = new AlertMessage("Item Carret is required");
            }else if(quantity.equals("")){
                AlertMessage msg = new AlertMessage("Item quantity is required");
            }else if(salePrice.equals("")){
                AlertMessage msg = new AlertMessage("Sale price is required");
            }else if(labourCost.equals("")){
                AlertMessage msg = new AlertMessage("Labour Cost is required, (0 if not applicable)");
            }else if(!Helper.priceFormatCheck(itemCarretText)){
                AlertMessage msg = new AlertMessage("Carret format is not accepted");
            }else if(!Helper.priceFormatCheck(quantity)){
                AlertMessage msg = new AlertMessage("Quantity format is not accepted");
            }else if(!Helper.priceFormatCheck(salePrice)){
                AlertMessage msg = new AlertMessage("Sale price format is not accepted");
            }else if(!Helper.priceFormatCheck(labourCost)){
                AlertMessage msg = new AlertMessage("Labour Cost format is not accepted");
            }else{

                //System.out.println(itemName+" "+itemCarretText+" "+quantity+" "+salePrice+" "+labourCost);
                HashMap map = new HashMap();
                map.put("itemName", itemName);
                map.put("carret", itemCarretText);
                map.put("quantity", quantity);
                map.put("salePrice", salePrice);
                map.put("laboutCost", labourCost);
                JSONObject jsonObject = new JSONObject();

                JSONArray array = JsonClass.getJsonArray(Constants.GENERATED_BARCODE_DATA);
                int id = array.size() + 1;
                map.put("id", id);
                jsonObject.putAll(map);

                array.add(jsonObject);
                FileWriter.write(Constants.GENERATED_BARCODE_DATA, array.toString());
                generate(id, path);
                dispose();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void generate(int id, String path) {
        Code39 barcode39 = new Code39();
        barcode39.setData("ID-" + id);
        try {
            //barcode39.drawBarcode("C:\\Users\\sarfraz\\Desktop\\barcode-code139.gif");
            barcode39.drawBarcode(path + "\\" + id + ".jpg");
        } catch (Exception ex) {
            Logger.getLogger(Barcode39Generator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SalePriceEt;
    private javax.swing.JTextField itemCarretEt;
    private javax.swing.JComboBox itemComboBox;
    private javax.swing.JTextField itemQuantityEt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField labourCostEt;
    private javax.swing.JLabel labourCostUnit;
    private javax.swing.JLabel pathTv;
    private javax.swing.JLabel quantityUnit;
    private javax.swing.JLabel salePriceUnit;
    private javax.swing.JLabel unitText;
    // End of variables declaration//GEN-END:variables
}
/*
new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" })
*/
