/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.shiva.krishna.jewellers;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author sarfraz
 */
public class EditStock extends javax.swing.JFrame {

    String id;

    /**
     * Creates new form EditStock
     */
    public EditStock(String id) {
        initComponents();
        this.id = id;
        displayPrevValues();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTv = new javax.swing.JTextField();
        weightTv = new javax.swing.JTextField();
        carretTv = new javax.swing.JTextField();
        percentageTv = new javax.swing.JTextField();
        ppTv = new javax.swing.JTextField();
        spTv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        motiWeightTv = new javax.swing.JTextField();
        metalWeightTv = new javax.swing.JTextField();
        metalNameTv = new javax.swing.JTextField();
        unit1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        unit2 = new javax.swing.JLabel();
        unit3 = new javax.swing.JLabel();
        unit4 = new javax.swing.JLabel();
        unit5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        avlPc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Item Name ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Weight");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Carret");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Purchase Price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Purchase %");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sale Price");

        nameTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        weightTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        carretTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        percentageTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ppTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        spTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Save The Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Moti & Stone Weight");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fine Metal Weight");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fine Metal Name");

        motiWeightTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        metalWeightTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        metalNameTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        unit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit1.setText("unit");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("%");

        unit2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit2.setText("/ unit");

        unit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit3.setText("/ unit");

        unit4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit4.setText("unit");

        unit5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unit5.setText("unit");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Available Quantity");

        avlPc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        avlPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avlPcActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Pieces");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(carretTv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(weightTv, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unit1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spTv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(ppTv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentageTv, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unit2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(unit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(metalWeightTv, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(metalNameTv, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(avlPc)
                                    .addComponent(motiWeightTv, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unit4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(avlPc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(weightTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit1)
                    .addComponent(jLabel7)
                    .addComponent(motiWeightTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carretTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(metalWeightTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(percentageTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(metalNameTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ppTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit3)
                    .addComponent(jButton1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateDetails();
        AlertMessage msg = new AlertMessage("Successfully Updated");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void avlPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avlPcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avlPcActionPerformed

    public void updateDetails(){
        JSONArray array = JsonClass.getJsonArray(Constants.STOCK_FILE);
        JSONArray newArray = new JSONArray();
        int flag=0;
        for (int i = array.size()-1; i >=0; i--) {
            JSONObject obj = (JSONObject) array.get(i);
            String cid = obj.get("id").toString();
            if (cid.equals(id) && flag==0) {
                flag = 1;
                obj.put("name", nameTv.getText());
                obj.put("purchasePrice", ppTv.getText());
                obj.put("salePrice", spTv.getText());
                obj.put("carret", carretTv.getText());
                obj.put("remainingPieces", avlPc.getText());
                obj.put("remainingWeight", weightTv.getText());
                obj.put("fineMetalName", metalNameTv.getText());
                newArray.add(obj);
                
            }else{
                newArray.add(obj);
            }
        }
        JSONArray a = new JSONArray();
        for(int i=newArray.size()-1;i>=0;i--){
            a.add(newArray.get(i));
        }
        FileWriter.write(Constants.STOCK_FILE, a.toString());
        
        flag=0;
        array = JsonClass.getJsonArray(Constants.PURCHASE_RECORD_FILE);
        JSONArray newArr = new JSONArray();
        for(int i=array.size()-1;i>=0;i--){
            JSONObject obj = (JSONObject) array.get(i);
            String cid = obj.get("stockID").toString();
            if(cid.equals(id) && flag==0){
                flag=1;
                obj.put("purchasePerc", percentageTv.getText());
                obj.put("quantity", weightTv.getText());
                obj.put("motiWeight", motiWeightTv.getText());
                obj.put("fineMetalWeight", metalWeightTv.getText());
                obj.put("fineMetalName", metalNameTv.getText());
                
                newArr.add(obj);
            }else{
                newArr.add(obj);
            }
        }
        JSONArray b = new JSONArray();
        for(int i=newArr.size()-1; i>=0;i--){
            b.add(newArr.get(i));
        }
        FileWriter.write(Constants.PURCHASE_RECORD_FILE, b.toString());
        ManageItems.refreshPage();
    }
    public void displayPrevValues() {
        JSONArray array = JsonClass.getJsonArray(Constants.STOCK_FILE);
        for (int i = array.size()-1; i >=0; i--) {
            JSONObject obj = (JSONObject) array.get(i);
            String cid = obj.get("id").toString();
            if (cid.equals(id)) {
                String name = obj.get("name").toString();
                String purchasePrice = obj.get("purchasePrice").toString();
                String salePrice = obj.get("salePrice").toString();
                String carret = obj.get("carret").toString();
                String unit = obj.get("unit").toString();
                String pcs = obj.get("remainingPieces").toString();
                String wt = obj.get("remainingWeight").toString();
                String metalName = obj.get("fineMetalName").toString();
                metalNameTv.setText(metalName);
                avlPc.setText(pcs);
                weightTv.setText(wt);
                nameTv.setText(name);
                ppTv.setText(purchasePrice);
                spTv.setText(salePrice);
                carretTv.setText(carret);
                unit1.setText(unit);
                unit2.setText(" / "+unit);
                unit3.setText(" / "+unit);
                unit4.setText(unit);
                unit5.setText(unit);
                break;
            }
        }
        
        array = JsonClass.getJsonArray(Constants.PURCHASE_RECORD_FILE);
        for(int i=array.size()-1;i>=0;i--){
            JSONObject obj = (JSONObject) array.get(i);
            String cid = obj.get("stockID").toString();
            if(cid.equals(id)){
                String perc = obj.get("purchasePerc").toString();
                //String weight = obj.get("quantity").toString();
                String motiWt = obj.get("motiWeight").toString();
                String metalWt = obj.get("fineMetalWeight").toString();
                String metalName = obj.get("fineMetalName").toString();
                percentageTv.setText(perc);
                //weightTv.setText(weight);
                motiWeightTv.setText(motiWt);
                metalWeightTv.setText(metalWt);
                
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avlPc;
    private javax.swing.JTextField carretTv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField metalNameTv;
    private javax.swing.JTextField metalWeightTv;
    private javax.swing.JTextField motiWeightTv;
    private javax.swing.JTextField nameTv;
    private javax.swing.JTextField percentageTv;
    private javax.swing.JTextField ppTv;
    private javax.swing.JTextField spTv;
    private javax.swing.JLabel unit1;
    private javax.swing.JLabel unit2;
    private javax.swing.JLabel unit3;
    private javax.swing.JLabel unit4;
    private javax.swing.JLabel unit5;
    private javax.swing.JTextField weightTv;
    // End of variables declaration//GEN-END:variables
}
