/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.shiva.krishna.jewellers;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author sarfraz
 */
public class SaleReport extends javax.swing.JFrame {

    String path = "";

    /**
     * Creates new form SaleReport
     */
    public SaleReport() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fromDateChoser = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toDateChoser = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        dir = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(650, 350));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        fromDateChoser.setCalendarPreferredSize(new java.awt.Dimension(350, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("From    :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("To       :");

        toDateChoser.setCalendarPreferredSize(new java.awt.Dimension(350, 220));

        jButton1.setText("Choose Directory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dir.setText("Not Chosen ....");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Save Sale Report as PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fromDateChoser, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                    .addComponent(toDateChoser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(fromDateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(toDateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(dir))
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        path = Helper.choseDir();
        dir.setText(path);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (path.equals("") || path.equals("cancelled")) {
            AlertMessage msg = new AlertMessage("Please choose directory to save report");
        } else {
            JSONParser parser = new JSONParser();

            JSONArray mainArray = JsonClass.getJsonArray(Constants.SALE_RECORD_FILE);
            Document document = new Document();

             SimpleDateFormat y = new SimpleDateFormat("dd-MM-yyyy");
            String from = y.format(fromDateChoser.getSelectedDate().getTime());
            String to = y.format(toDateChoser.getSelectedDate().getTime());
            String file  = path+"/"+from+"--"+to+"_sale_report.pdf";
            try {
                PdfWriter.getInstance(document, new FileOutputStream(file));                    //change the name of the file according to the cudtomer id
            } catch (DocumentException ex) {
                Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
            }
            document.open();

           

            Paragraph header = new Paragraph("Sale Report : " + from + " - " + to, FontFactory.getFont(FontFactory.TIMES_BOLD, 10, Font.ITALIC, BaseColor.BLACK));
            header.setAlignment(Element.ALIGN_CENTER);
            try {
                document.add(header);
            } catch (DocumentException ex) {
                Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
            }

            for (int i = 0; i < mainArray.size(); i++) {
                try {
                    Object o = parser.parse(mainArray.get(i).toString());
                    JSONArray array = (JSONArray) o;
                    //System.out.println(array);

                    Object obj = parser.parse(array.get(0).toString());
                    JSONObject jsonObject = (JSONObject) obj;
                    String customerName = jsonObject.get("customerName").toString();
                    String customerPhone = jsonObject.get("customerPhone").toString();
                    String customerAddress = jsonObject.get("customerAddress").toString();
                    String customerId  = jsonObject.get("customerID").toString();
                    String billDate = jsonObject.get("billDate").toString();
                    String totalAmt = jsonObject.get("totalAmount").toString();
                    String discount = jsonObject.get("discount").toString();

                    Date targetDate = new SimpleDateFormat("dd/MM/yy", Locale.ENGLISH).parse(billDate);
                    y = new SimpleDateFormat("dd/MM/yy");

                    Date toDate = toDateChoser.getSelectedDate().getTime();
                    Date fromDate = fromDateChoser.getSelectedDate().getTime();

                    String toDateStr = y.format(toDate);
                    String fromDateStr = y.format(fromDate);

                    Date toD = new SimpleDateFormat("dd/MM/yy", Locale.ENGLISH).parse(toDateStr);
                    Date fromD = new SimpleDateFormat("dd/MM/yy", Locale.ENGLISH).parse(fromDateStr);

                    if (DateCompare.inRange(fromD, targetDate, toD)) {
                        Paragraph p = new Paragraph();
                        for (int j = 0; j < 130; j++) {
                            p.add("-");
                        }
                        document.add(p);

                        document.add(new Paragraph("Customer Id           :    "+customerId));
                        document.add(new Paragraph("Customer Name    :     " + customerName));
                        document.add(new Paragraph("Phone                    :     " + customerPhone));
                        document.add(new Paragraph("Address                 :     " + customerAddress));
                        document.add(new Paragraph("Bill Date                 :     " + billDate));
                        document.add(new Paragraph(" "));

                        //sn, stockid, name, qty, carret, sp, lc, total , 
                        float[] columnWidths = new float[]{2f, 2f, 3f, 3f, 2f, 3f, 3f, 3f};
                        PdfPTable table = new PdfPTable(8);
                        table.setWidthPercentage(100);
                        table.setWidths(columnWidths);

                        table.addCell("S No.");
                        table.addCell("Stock Id");
                        table.addCell("Item Name");
                        table.addCell("Qty");
                        table.addCell("Carret");
                        table.addCell("Sale Price");
                        table.addCell("Labour Cost");
                        table.addCell("Total");

                        for (int j = 1; j < array.size(); j++) {
                            System.out.println(array.toString());
                            obj = parser.parse(array.get(j).toString());
                            jsonObject = (JSONObject) obj;

                            String itemName = jsonObject.get("itemName").toString();
                            String carret = jsonObject.get("carret").toString();
                            String unit = jsonObject.get("unit").toString();
                            String labourCost = jsonObject.get("labourCost").toString();
                            String total = jsonObject.get("total").toString();
                            String quantity = jsonObject.get("quantity").toString();
                            String salePrice = jsonObject.get("salePrice").toString();
                            String stockID = jsonObject.get("stockID").toString();
                            String sn = jsonObject.get("sn").toString();
                            String date = jsonObject.get("billDate").toString();

                            table.addCell(sn);
                            table.addCell(stockID);
                            table.addCell(itemName);
                            table.addCell(quantity + " " + unit);
                            table.addCell(carret);
                            table.addCell(salePrice);
                            table.addCell(labourCost);
                            table.addCell(total);

                        }
                        document.add(table);

                        
                        Paragraph t = new Paragraph("Total Amount : " + totalAmt);
                        t.setAlignment(Element.ALIGN_RIGHT);
                        document.add(t);
                        
                        t = new Paragraph("Discount Offered : "+discount);
                        t.setAlignment(Element.ALIGN_RIGHT);
                        document.add(t);
                    }

                } catch (ParseException ex) {
                    Logger.getLogger(SearchSale.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
                } catch (java.text.ParseException ex) {
                    Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            try {
                Paragraph p = new Paragraph();
                for (int j = 0; j < 130; j++) {
                    p.add("-");
                }
                document.add(p);
            } catch (DocumentException ex) {
                Logger.getLogger(SaleReport.class.getName()).log(Level.SEVERE, null, ex);
            }
            document.close();
            dispose();
            AlertMessage msg = new AlertMessage("Report saved - "+path);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dir;
    private datechooser.beans.DateChooserCombo fromDateChoser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private datechooser.beans.DateChooserCombo toDateChoser;
    // End of variables declaration//GEN-END:variables
}
